<?php require __DIR__.'/helpers.php';
require_once __DIR__ . '/vendor/autoload.php';
$in=input_json();
$numero='INFORME SEFAB-'.date('Y').'-'.str_pad((string)rand(1,9999),4,'0',STR_PAD_LEFT);
$cliente=$in['cliente_nombre']??''; $doc=$in['cliente_documento']??''; $asunto=$in['asunto']??''; $fecha=$in['fecha_informe']??date('Y-m-d'); $areasTxt=$in['areas']??'';
$pdfFile='informe_'.date('Ymd_His').'_'.rand(100,999).'.pdf';
$path=__DIR__.'/uploads/informes/'.$pdfFile;
$pdf=new TCPDF('P','mm','A4',true,'UTF-8',false);$pdf->SetCreator('SEFAB');$pdf->SetAuthor('SEFAB');$pdf->SetTitle($numero);$pdf->setPrintHeader(false);$pdf->setPrintFooter(false);$pdf->AddPage();$pdf->SetFont('helvetica','',10);
$areas=''; foreach(preg_split('/\r\n|\r|\n/', $areasTxt) as $a){ if(trim($a)!=='') $areas.='<li>'.htmlspecialchars(trim($a)).'</li>'; }
$html='<h2 style="text-align:center">'.$numero.'</h2><p><b>RUC:</b> 10454870811</p><p><b>Señores:</b> '.htmlspecialchars($cliente).'<br><b>DNI/RUC:</b> '.htmlspecialchars($doc).'<br><b>Asunto:</b> '.htmlspecialchars($asunto).'<br><b>Fecha:</b> Trujillo, '.htmlspecialchars($fecha).'</p><hr><h3>1. DATOS GENERALES</h3><p><b>Tipo de servicio:</b> Mantenimiento Preventivo de Aires Acondicionados.</p><p><b>Áreas intervenidas:</b></p><ul>'.$areas.'</ul><h3>2. OBJETIVO DEL MANTENIMIENTO</h3><p>Garantizar el correcto funcionamiento, eficiencia operativa y prolongación de la vida útil de los equipos de aire acondicionado.</p><h3>3. ALCANCE DEL SERVICIO</h3><p>Revisión, limpieza, verificación y ajustes básicos en unidades evaporadoras y condensadoras.</p><h3>4. ACTIVIDADES REALIZADAS</h3><ul><li>Limpieza serpentín condensador y evaporador.</li><li>Lavado de filtros.</li><li>Lubricación de motores y verificación mecánica.</li><li>Toma de voltaje y amperaje.</li><li>Revisión de contactores, capacitores y sensores.</li><li>Verificación de tuberías, fugas y presión de refrigerante.</li><li>Pruebas operativas y validación de enfriamiento.</li></ul><h3>5. RESULTADOS</h3><p>Los equipos intervenidos se encuentran operativos, mejorando la eficiencia y calidad del aire. No se detectaron fallas críticas durante el mantenimiento preventivo.</p><h3>6. OBSERVACIONES</h3><p>Se recomienda mantener limpias y despejadas las unidades condensadoras, considerando el entorno industrial y salino.</p><h3>7. RECOMENDACIONES</h3><p>Mantener el programa preventivo periódico e incrementar la frecuencia en ambientes con polvo industrial y brisa marina.</p><h3>8. CONCLUSIÓN</h3><p>El mantenimiento ejecutado permitió restablecer condiciones adecuadas de funcionamiento y reducir riesgos de falla.</p><br><br><p>Atentamente,</p><br><br><p>____________________________<br>Tec. Felix Estuardo Cruz Alayo<br>Gerente General</p>';
$pdf->writeHTML($html,true,false,true,false,'');$pdf->Output($path,'F');
$pdo->prepare('INSERT INTO informes(numero_informe,cliente_nombre,cliente_documento,asunto,fecha_informe,correo_destino,archivo_pdf,estado) VALUES(?,?,?,?,?,?,?,1)')->execute([$numero,$cliente,$doc,$asunto,$fecha,$in['correo_destino']??'',$pdfFile]);$id=$pdo->lastInsertId();
responder(true,'Informe generado',['informe'=>['id'=>$id,'numero_informe'=>$numero,'cliente_nombre'=>$cliente,'fecha_informe'=>$fecha,'asunto'=>$asunto,'pdf_url'=>$config['base_url'].'uploads/informes/'.$pdfFile]]);
